[package]
name = "vertex"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Vertex Swarm node binary"

[[bin]]
name = "vertex"
path = "src/main.rs"

[dependencies]
vertex-node-builder.workspace = true
vertex-swarm-api.workspace = true
vertex-swarm-node.workspace = true
eyre.workspace = true
hex.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
