[package]
name = "vertex-node-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generic node type definitions for Vertex"

[lints]
workspace = true

[dependencies]
# Task executor
vertex-tasks.workspace = true

# Derive macros
auto_impl.workspace = true

[features]
default = ["std"]
std = []
