[package]
name = "vertex-net-pseudosettle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Pseudosettle protocol for Swarm bandwidth accounting"
build = "build.rs"

[lints]
workspace = true

[dependencies]
## vertex
vertex-net-codec.workspace = true
vertex-net-headers.workspace = true

## async
futures.workspace = true

## p2p
asynchronous-codec.workspace = true
quick-protobuf.workspace = true
quick-protobuf-codec.workspace = true
libp2p.workspace = true

## crypto
alloy-primitives.workspace = true

## misc
bytes.workspace = true
thiserror.workspace = true

## tracing
tracing.workspace = true

[build-dependencies]
pb-rs.workspace = true
walkdir.workspace = true

[dev-dependencies]
