[package]
name = "vertex-swarm-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Swarm component builder infrastructure"

[lints]
workspace = true

[dependencies]
# vertex
vertex-swarm-api.workspace = true
vertex-bandwidth-core.workspace = true
vertex-client-kademlia.workspace = true
vertex-tasks.workspace = true

# misc
tracing.workspace = true
