[package]
name = "vertex-node-commands"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Generic CLI infrastructure for Vertex nodes"

[lints]
workspace = true

[dependencies]
# vertex - generic infrastructure only
vertex-node-builder.workspace = true
vertex-node-core.workspace = true
vertex-tasks.workspace = true

# cli
clap = { workspace = true, features = ["derive", "env"] }

# async
tokio = { workspace = true, features = ["macros"] }

# misc
color-eyre.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile = "3"
