[package]
name = "vertex-net-pushsync"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Swarm pushsync protocol for chunk push/receipt"

[dependencies]
## vertex
vertex-net-codec.workspace = true
vertex-net-headers.workspace = true
vertex-primitives.workspace = true

## p2p
libp2p.workspace = true
asynchronous-codec.workspace = true

## protobuf
quick-protobuf.workspace = true
quick-protobuf-codec.workspace = true

## async
futures.workspace = true

## misc
bytes.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
pb-rs.workspace = true
walkdir.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }

[lints]
workspace = true
