[package]
name = "vertex-swarm-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# Internal dependencies
nectar-primitives = { workspace = true }
vertex-node-api = { workspace = true }
vertex-node-types = { workspace = true }
vertex-swarmspec = { workspace = true }
vertex-swarm-primitives = { workspace = true }
vertex-tasks = { workspace = true }

# Alloy
alloy-primitives = { workspace = true }
alloy-signer = { workspace = true }

# External dependencies
auto_impl = "1.1"
bytes = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
async-trait = "0.1"
tracing = { workspace = true }
strum = { workspace = true }

# Optional serde support
serde = { workspace = true, features = ["derive"], optional = true }

[features]
default = ["std"]
std = []
serde = ["dep:serde", "vertex-swarm-primitives/serde"]
