[package]
name = "vertex-net-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
## nectar primitives
nectar-primitives.workspace = true
nectar-swarms.workspace = true

## vertex primitives
vertex-net-primitives-traits.workspace = true

alloy-primitives = { workspace = true, features = ["arbitrary"] }
alloy-signer.workspace = true
alloy-signer-local.workspace = true

libp2p.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
thiserror.workspace = true

bytes.workspace = true

# DNS resolution
hickory-resolver = { version = "0.25.0-alpha.5", features = ["tokio-runtime"] }
tracing = { workspace = true }

[dev-dependencies]
arbitrary.workspace = true
proptest.workspace = true
proptest-arbitrary-interop.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }

[lints]
workspace = true
