[package]
name = "vertex-node-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Type-state node builder for Vertex"

[lints]
workspace = true

[dependencies]
vertex-node-api.workspace = true
vertex-node-core.workspace = true
vertex-rpc-server.workspace = true
vertex-tasks.workspace = true

async-trait.workspace = true
eyre.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["sync", "signal"] }

[features]
default = []
